name: Build App

on:
  push:
    tags:
      - "v*" # only build on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Make (build and package) Electron app
        run: npm run make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: out/make/
      - name: Publish to GitHub Releases
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
